entity_kinds = {
    'a': "array",
    'A': "array type",
    'b': "boolean",
    'B': "boolean type",
    'c': "class wide",
    'C': "class wide type",
    'd': "decimal fixed point",
    'D': "decimal fixed point type",
    'e': "enumeration",
    'E': "enumeration type",
    'f': "floating point",
    'F': "floating point type",
    'g': "macro",
    'G': "function macro",
    'h': "interface",
    'H': "abstract record type",
    'i': "integer",
    'I': "integer type",
    'j': "class instance",
    'J': "class",
    'k': "generic package",
    'K': "package",
    'l': "loop label",
    'L': "statement label",
    'm': "unsigned integer",
    'M': "unsigned integer type",
    'n': "enumeration literal",
    'N': "named number",
    'o': "fixed point",
    'O': "fixed point type",
    'p': "pointer",
    'P': "access type",
    'q': "block label",
    'Q': "include file",
    'r': "record",
    'R': "record type",
    's': "string",
    'S': "string type",
    't': "task",
    'T': "task type",
    'u': "generic procedure",
    'U': "procedure",
    'v': "generic function",
    'V': "function",
    'w': "protected object",
    'W': "protected type",
    'x': "abstract procedure",
    'X': "exception",
    'y': "abstract function",
    'Y': "entry",
    'z': "unknown",
    'Z': "unknown",
    '+': "generic formal",
    '@': "abstract state",
    '*': "private object"
}

function_kinds = ['G', 'u', 'U', 'v', 'V', 'x', 'y']
package_kinds = ['K', 'k']
